In [4]:
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 20)

In [5]:
matches = pd.read_csv("../data/matches_1930_2022.csv")
rankings = pd.read_csv("../data/fifa_ranking_2026-06-08.csv")
world_cup = pd.read_csv("../data/world_cup.csv")

In [6]:
print("MATCHES SHAPE")
print(matches.shape)

print("\nRANKINGS SHAPE")
print(rankings.shape)

print("\nWORLD CUP SHAPE")
print(world_cup.shape)

MATCHES SHAPE
(964, 44)

RANKINGS SHAPE
(211, 8)

WORLD CUP SHAPE
(22, 9)

In [7]:
print("MATCHES COLUMNS")
print(matches.columns.tolist())

print("\nRANKINGS COLUMNS")
print(rankings.columns.tolist())

print("\nWORLD CUP COLUMNS")
print(world_cup.columns.tolist())

MATCHES COLUMNS
['home_team', 'away_team', 'home_score', 'home_xg', 'home_penalty', 'away_score', 'away_xg', 'away_penalty', 'home_manager', 'home_captain', 'away_manager', 'away_captain', 'Attendance', 'Venue', 'Officials', 'Round', 'Date', 'Score', 'Referee', 'Notes', 'Host', 'Year', 'home_goal', 'away_goal', 'home_goal_long', 'away_goal_long', 'home_own_goal', 'away_own_goal', 'home_penalty_goal', 'away_penalty_goal', 'home_penalty_miss_long', 'away_penalty_miss_long', 'home_penalty_shootout_goal_long', 'away_penalty_shootout_goal_long', 'home_penalty_shootout_miss_long', 'away_penalty_shootout_miss_long', 'home_red_card', 'away_red_card', 'home_yellow_red_card', 'away_yellow_red_card', 'home_yellow_card_long', 'away_yellow_card_long', 'home_substitute_in_long', 'away_substitute_in_long']

RANKINGS COLUMNS
['team', 'team_code', 'association', 'rank', 'previous_rank', 'points', 'previous_points', 'rated_matches']

WORLD CUP COLUMNS
['Year', 'Host', 'Teams', 'Champion', 'Runner-Up', 'TopScorrer', 'Attendance', 'AttendanceAvg', 'Matches']

In [8]:
print("MATCHES MISSING VALUES")
print(matches.isnull().sum().sort_values(ascending=False).head(20))

print("\nRANKINGS MISSING VALUES")
print(rankings.isnull().sum().sort_values(ascending=False).head(20))

print("\nWORLD CUP MISSING VALUES")
print(world_cup.isnull().sum().sort_values(ascending=False).head(20))

MATCHES MISSING VALUES
home_penalty_miss_long             958
away_penalty_miss_long             955
away_own_goal                      947
home_yellow_red_card               941
home_penalty_shootout_miss_long    940
away_penalty_shootout_miss_long    934
away_yellow_red_card               933
home_penalty_shootout_goal_long    930
away_penalty_shootout_goal_long    930
home_penalty                       929
away_penalty                       929
home_own_goal                      925
home_red_card                      913
away_red_card                      910
Notes                              891
away_penalty_goal                  880
home_penalty_goal                  848
away_xg                            836
home_xg                            836
away_goal                          393
dtype: int64

RANKINGS MISSING VALUES
team               0
team_code          0
association        0
rank               0
previous_rank      0
points             0
previous_points    0
rated_matches      0
dtype: int64

WORLD CUP MISSING VALUES
Year             0
Host             0
Teams            0
Champion         0
Runner-Up        0
TopScorrer       0
Attendance       0
AttendanceAvg    0
Matches          0
dtype: int64

In [9]:
print("MATCHES SAMPLE")
display(matches.head())

print("RANKINGS SAMPLE")
display(rankings.head())

print("WORLD CUP SAMPLE")
display(world_cup.head())

MATCHES SAMPLE

,home_team,away_team,home_score,home_xg,home_penalty,away_score,away_xg,away_penalty,home_manager,home_captain,away_manager,away_captain,Attendance,Venue,Officials,Round,Date,Score,Referee,Notes,Host,Year,home_goal,away_goal,home_goal_long,away_goal_long,home_own_goal,away_own_goal,home_penalty_goal,away_penalty_goal,home_penalty_miss_long,away_penalty_miss_long,home_penalty_shootout_goal_long,away_penalty_shootout_goal_long,home_penalty_shootout_miss_long,away_penalty_shootout_miss_long,home_red_card,away_red_card,home_yellow_red_card,away_yellow_red_card,home_yellow_card_long,away_yellow_card_long,home_substitute_in_long,away_substitute_in_long
0,Argentina,France,3,3.3,4.0,3,2.2,2.0,Lionel Scaloni,Lionel Messi,Didier Deschamps,Hugo Lloris,88966,"Lusail Iconic Stadium, Lusail",Szymon Marciniak (Referee) · Paweł Sokolnicki ...,Final,2022-12-18,(4) 3–3 (2),Szymon Marciniak,Argentina won on penalty kicks following extra...,Qatar,2022,Ángel Di María · 36|Lionel Messi · 108,Kylian Mbappé · 81,['36&rsquor;|2:0|Ángel Di María|Assist:|Alexis...,['81&rsquor;|2:2|Kylian Mbappé|Assist:|Marcus ...,NaN,NaN,Lionel Messi (P) · 23,Kylian Mbappé (P) · 80|Kylian Mbappé (P) · 118,NaN,NaN,"['2|1:1|Lionel Messi', '4|2:1|Paulo Dybala', '...","['1|0:1|Kylian Mbappé', '7|3:2|Randal Kolo Mua...",NaN,"['3|1:1|Kingsley Coman', '5|2:1|Aurélien Tchou...",NaN,NaN,NaN,NaN,"['45+7&rsquor;|2:0|Enzo Fernández', '90+8&rsqu...","['55&rsquor;|2:0|Adrien Rabiot', '87&rsquor;|2...",['64&rsquor;|2:0|Marcos Acuña|for Ángel Di Mar...,['41&rsquor;|2:0|Randal Kolo Muani|for Ousmane...
1,Croatia,Morocco,2,0.7,NaN,1,1.2,NaN,Zlatko Dalić,Luka Modrić,Hoalid Regragui,Hakim Ziyech,44137,"Khalifa International Stadium, Doha",Abdulrahman Ibrahim Al Jassim (Referee) · Tale...,Third-place match,2022-12-17,2–1,Abdulrahman Ibrahim Al Jassim,NaN,Qatar,2022,Joško Gvardiol · 7|Mislav Oršić · 42,Achraf Dari · 9,['7&rsquor;|1:0|Joško Gvardiol|Assist:|Ivan Pe...,['9&rsquor;|1:1|Achraf Dari'],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['69&rsquor;|2:1|Azzedine Ounahi', '84&rsquor;...",['61&rsquor;|2:1|Nikola Vlašić|for Andrej Kram...,['46&rsquor;|2:1|Ilias Chair|for Abdelhamid Sa...
2,France,Morocco,2,2.0,NaN,0,0.9,NaN,Didier Deschamps,Hugo Lloris,Hoalid Regragui,Romain Saïss,68294,"Al Bayt Stadium, Al Khor",César Arturo Ramos (Referee) · Alberto Morín (...,Semi-finals,2022-12-14,2–0,César Arturo Ramos,NaN,Qatar,2022,Theo Hernández · 5|Randal Kolo Muani · 79,NaN,"['5&rsquor;|1:0|Theo Hernández', '79&rsquor;|2...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['27&rsquor;|1:0|Sofiane Boufal'],['65&rsquor;|1:0|Marcus Thuram|for Olivier Gir...,['21&rsquor;|1:0|Selim Amallah|for Romain Saïs...
3,Argentina,Croatia,3,2.3,NaN,0,0.5,NaN,Lionel Scaloni,Lionel Messi,Zlatko Dalić,Luka Modrić,88966,"Lusail Iconic Stadium, Lusail",Daniele Orsato (Referee) · Ciro Carbone (AR1) ...,Semi-finals,2022-12-13,3–0,Daniele Orsato,NaN,Qatar,2022,Julián Álvarez · 39|Julián Álvarez · 69,NaN,"['39&rsquor;|2:0|Julián Álvarez', '69&rsquor;|...",NaN,NaN,NaN,Lionel Messi (P) · 34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['68&rsquor;|2:0|Cristian Romero', '71&rsquor;...","['32&rsquor;|0:0|Mateo Kovačić', '32&rsquor;|0...",['62&rsquor;|2:0|Lisandro Martínez|for Leandro...,"['46&rsquor;|2:0|Mislav Oršić|for Borna Sosa',..."
4,Morocco,Portugal,1,1.4,NaN,0,0.9,NaN,Hoalid Regragui,Romain Saïss,Fernando Santos,Pepe,44198,"Al Thumama Stadium, ath-Thumāma",Facundo Tello (Referee) · Ezequiel Brailovsky ...,Quarter-finals,2022-12-10,1–0,Facundo Tello,NaN,Qatar,2022,Youssef En-Nesyri · 42,NaN,['42&rsquor;|1:0|Youssef En-Nesyri|Assist:|Yah...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Walid Cheddira · 90+3,NaN,"['70&rsquor;|1:0|Achraf Dari', '90+1&rsquor;|1...",['87&rsquor;|1:0|Vitinha'],['57&rsquor;|1:0|Achraf Dari|for Romain Saïss'...,['51&rsquor;|1:0|João Cancelo|for Raphaël Guer...

RANKINGS SAMPLE

,team,team_code,association,rank,previous_rank,points,previous_points,rated_matches
0,Argentina,ARG,CONMEBOL,1,3,1876.118331,1874.814835,59
1,Spain,ESP,UEFA,2,2,1873.013187,1876.395199,56
2,France,FRA,UEFA,3,1,1869.428449,1877.322731,57
3,England,ENG,UEFA,4,4,1827.048678,1825.965482,57
4,Portugal,POR,UEFA,5,5,1766.177547,1763.834406,56

WORLD CUP SAMPLE

,Year,Host,Teams,Champion,Runner-Up,TopScorrer,Attendance,AttendanceAvg,Matches
0,2022,Qatar,32,Argentina,France,Kylian Mbappé - 8,3404252,53191,64
1,2018,Russia,32,France,Croatia,Harry Kane - 6,3031768,47371,64
2,2014,Brazil,32,Germany,Argentina,James Rodríguez - 6,3429873,53592,64
3,2010,South Africa,32,Spain,Netherlands,"Wesley Sneijder, Thomas Müller... - 5",3178856,49670,64
4,2006,Germany,32,Italy,France,Miroslav Klose - 5,3352605,52384,64

In [10]:
print("Unique Teams in Rankings")

print(rankings["team"].nunique())
rankings["team"].sort_values().head()

Unique Teams in Rankings
211

168       Afghanistan
65            Albania
27            Algeria
191    American Samoa
171           Andorra
Name: team, dtype: object

In [11]:
print(matches["Year"].min())
print(matches["Year"].max())

print(matches["Round"].value_counts().head(20))

1930
2022
Round
Group stage             587
Round of 16              97
Quarter-finals           70
First round              48
Semi-finals              38
First group stage        36
Second round             24
Final                    21
Third-place match        20
Second group stage       12
Final stage               6
Group stage play-off      5
Name: count, dtype: int64

In [12]:
summary = pd.DataFrame({
    "Dataset": ["Matches", "Rankings", "World Cup"],
    "Rows": [
        matches.shape[0],
        rankings.shape[0],
        world_cup.shape[0]
    ],
    "Columns": [
        matches.shape[1],
        rankings.shape[1],
        world_cup.shape[1]
    ]
})

summary

     Dataset  Rows  Columns
0    Matches   964       44
1   Rankings   211        8
2  World Cup    22        9

In [1]:
import pandas as pd

df = pd.read_csv("D:\PROJETS\FIFA WC 26\data\knockout_slots.csv")

print(df.head(10))

   match_id        round  multiplier              date_utc  \
0        73  Round of 32           1  2026-06-28T19:00:00Z
1        74  Round of 32           1  2026-06-29T17:00:00Z
2        75  Round of 32           1  2026-06-29T20:30:00Z
3        76  Round of 32           1  2026-06-30T01:00:00Z
4        77  Round of 32           1  2026-06-30T17:00:00Z
5        78  Round of 32           1  2026-06-30T21:00:00Z
6        79  Round of 32           1  2026-07-01T01:00:00Z
7        80  Round of 32           1  2026-07-01T16:00:00Z
8        81  Round of 32           1  2026-07-01T20:00:00Z
9        82  Round of 32           1  2026-07-02T00:00:00Z

                              venue          slot_home  \
0         SoFi Stadium, Los Angeles  Runner-up Group A
1              NRG Stadium, Houston     Winner Group C
2          Gillette Stadium, Boston     Winner Group E
3           Estadio BBVA, Monterrey     Winner Group F
4              AT&T Stadium, Dallas  Runner-up Group E
5  MetLife Stadium, East Rutherford     Winner Group I
6       Estadio Azteca, Mexico City     Winner Group A
7    Mercedes-Benz Stadium, Atlanta     Winner Group L
8              Lumen Field, Seattle     Winner Group G
9       Levi's Stadium, Santa Clara     Winner Group D

                     slot_away
0            Runner-up Group B
1            Runner-up Group F
2  Best 3rd (Groups A/B/C/D/F)
3            Runner-up Group C
4            Runner-up Group I
5  Best 3rd (Groups C/D/F/G/H)
6  Best 3rd (Groups C/E/F/H/I)
7  Best 3rd (Groups E/H/I/J/K)
8  Best 3rd (Groups A/E/H/I/J)
9  Best 3rd (Groups B/E/F/I/J)

In [2]:
df[
[
"match_id",
"round",
"slot_home",
"slot_away"
]
]

,match_id,round,slot_home,slot_away
0,73,Round of 32,Runner-up Group A,Runner-up Group B
1,74,Round of 32,Winner Group C,Runner-up Group F
2,75,Round of 32,Winner Group E,Best 3rd (Groups A/B/C/D/F)
3,76,Round of 32,Winner Group F,Runner-up Group C
4,77,Round of 32,Runner-up Group E,Runner-up Group I
5,78,Round of 32,Winner Group I,Best 3rd (Groups C/D/F/G/H)
6,79,Round of 32,Winner Group A,Best 3rd (Groups C/E/F/H/I)
7,80,Round of 32,Winner Group L,Best 3rd (Groups E/H/I/J/K)
8,81,Round of 32,Winner Group G,Best 3rd (Groups A/E/H/I/J)
9,82,Round of 32,Winner Group D,Best 3rd (Groups B/E/F/I/J)
10,83,Round of 32,Runner-up Group K,Runner-up Group L
11,84,Round of 32,Winner Group H,Runner-up Group J
12,85,Round of 32,Winner Group B,Best 3rd (Groups E/F/G/I/J)
13,86,Round of 32,Runner-up Group D,Runner-up Group G
14,87,Round of 32,Winner Group J,Runner-up Group H
15,88,Round of 32,Winner Group K,Best 3rd (Groups D/E/I/J/L)
16,89,Round of 16,Winner Match 73,Winner Match 75
17,90,Round of 16,Winner Match 74,Winner Match 77
18,91,Round of 16,Winner Match 76,Winner Match 78
19,92,Round of 16,Winner Match 79,Winner Match 80
20,93,Round of 16,Winner Match 83,Winner Match 84
21,94,Round of 16,Winner Match 81,Winner Match 82
22,95,Round of 16,Winner Match 86,Winner Match 88
23,96,Round of 16,Winner Match 85,Winner Match 87
24,97,Quarter-final,Winner Match 89,Winner Match 90
25,98,Quarter-final,Winner Match 93,Winner Match 94
26,99,Quarter-final,Winner Match 91,Winner Match 92
27,100,Quarter-final,Winner Match 95,Winner Match 96
28,101,Semi-final,Winner Match 97,Winner Match 98
29,102,Semi-final,Winner Match 99,Winner Match 100
30,103,Third-place playoff,Loser Match 101,Loser Match 102
31,104,Final,Winner Match 101,Winner Match 102